const products = [
  {
    id: 0,
    name: "Product #0",
    colors: ["pink", "maroon"],
    sizes: ["S", "XL"],
    availability: ["Paris"],
  },
  {
    id: 1,
    name: "Product #1",
    colors: ["blue", "green", "maroon"],
    sizes: ["M"],
    availability: ["London", "Prague"],
  },
  {
    id: 2,
    name: "Product #2",
    colors: ["gray", "maroon"],
    sizes: ["XXS", "L"],
    availability: ["Budapest"],
  },
  {
    id: 3,
    name: "Product #3",
    colors: ["gray"],
    sizes: ["XS", "M", "XXL"],
    availability: ["Budapest", "Prague", "Berlin", "Stockholm"],
  },
  {
    id: 4,
    name: "Product #4",
    colors: ["green"],
    sizes: ["XXS"],
    availability: ["Copenhagen", "Berlin", "Stockholm"],
  },
  {
    id: 5,
    name: "Product #5",
    colors: ["blue", "pink", "red"],
    sizes: ["XS"],
    availability: ["Paris", "Prague", "Berlin", "Stockholm"],
  },
  {
    id: 6,
    name: "Product #6",
    colors: ["yellow"],
    sizes: ["M", "XXXS"],
    availability: ["London", "Prague"],
  },
  {
    id: 7,
    name: "Product #7",
    colors: ["pink"],
    sizes: ["XXS", "M", "XXXS"],
    availability: ["Prague", "Berlin"],
  },
  {
    id: 8,
    name: "Product #8",
    colors: ["blue"],
    sizes: ["XXS", "XXL", "XXXS"],
    availability: ["Prague", "Berlin"],
  },
  {
    id: 9,
    name: "Product #9",
    colors: ["white", "green", "gray"],
    sizes: ["S"],
    availability: ["Budapest"],
  },
  {
    id: 10,
    name: "Product #10",
    colors: ["pink", "magenta"],
    sizes: ["S", "XXL"],
    availability: ["London"],
  },
  {
    id: 11,
    name: "Product #11",
    colors: ["blue"],
    sizes: ["S", "L"],
    availability: ["Amsterdam", "Paris", "Copenhagen", "Budapest"],
  },
  {
    id: 12,
    name: "Product #12",
    colors: ["pink", "yellow"],
    sizes: ["M"],
    availability: ["Budapest", "Berlin"],
  },
  {
    id: 13,
    name: "Product #13",
    colors: ["magenta", "gray"],
    sizes: ["XXS", "XS"],
    availability: ["Budapest"],
  },
  {
    id: 14,
    name: "Product #14",
    colors: ["pink", "red", "yellow"],
    sizes: ["XXS", "XL"],
    availability: ["Copenhagen"],
  },
  {
    id: 15,
    name: "Product #15",
    colors: ["white", "green"],
    sizes: ["M"],
    availability: ["London", "Budapest"],
  },
  {
    id: 16,
    name: "Product #16",
    colors: ["white", "green", "gray"],
    sizes: ["XXS", "S"],
    availability: ["Copenhagen", "Prague"],
  },
  {
    id: 17,
    name: "Product #17",
    colors: ["gray"],
    sizes: ["XXS"],
    availability: ["Amsterdam"],
  },
  {
    id: 18,
    name: "Product #18",
    colors: ["blue", "pink", "green", "gray"],
    sizes: ["M"],
    availability: ["Amsterdam", "Paris"],
  },
  {
    id: 19,
    name: "Product #19",
    colors: ["black", "white", "green"],
    sizes: ["XXS", "M", "L", "XXL"],
    availability: ["London", "Paris"],
  },
  {
    id: 20,
    name: "Product #20",
    colors: ["black", "white", "green", "gray"],
    sizes: ["M"],
    availability: ["London", "Paris", "Copenhagen", "Budapest", "Berlin"],
  },
  {
    id: 21,
    name: "Product #21",
    colors: ["gray"],
    sizes: ["XXL"],
    availability: ["Amsterdam"],
  },
  {
    id: 22,
    name: "Product #22",
    colors: ["blue", "red"],
    sizes: ["M", "L"],
    availability: ["Prague", "Berlin"],
  },
  {
    id: 23,
    name: "Product #23",
    colors: ["red"],
    sizes: ["XXL"],
    availability: ["Paris"],
  },
  {
    id: 24,
    name: "Product #24",
    colors: ["black", "blue", "red", "green", "gray"],
    sizes: ["M"],
    availability: ["Copenhagen"],
  },
  {
    id: 25,
    name: "Product #25",
    colors: ["red"],
    sizes: ["M"],
    availability: ["Amsterdam", "Paris", "Copenhagen", "Budapest"],
  },
  {
    id: 26,
    name: "Product #26",
    colors: ["black", "white", "red"],
    sizes: ["XXL"],
    availability: ["London", "Budapest"],
  },
  {
    id: 27,
    name: "Product #27",
    colors: ["white", "red", "yellow"],
    sizes: ["XXS", "L"],
    availability: ["London", "Budapest"],
  },
  {
    id: 28,
    name: "Product #28",
    colors: ["white"],
    sizes: ["XS", "XL"],
    availability: ["London", "Copenhagen", "Budapest", "Prague"],
  },
  {
    id: 29,
    name: "Product #29",
    colors: ["white", "pink"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 30,
    name: "Product #30",
    colors: ["white"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 31,
    name: "Product #31",
    colors: ["white", "pink"],
    sizes: ["L"],
    availability: ["Amsterdam", "Budapest"],
  },
  {
    id: 32,
    name: "Product #32",
    colors: ["black", "green"],
    sizes: ["S", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 33,
    name: "Product #33",
    colors: ["green", "gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 34,
    name: "Product #34",
    colors: ["magenta"],
    sizes: ["M"],
    availability: ["Amsterdam", "Copenhagen", "Budapest"],
  },
  {
    id: 35,
    name: "Product #35",
    colors: ["yellow"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 36,
    name: "Product #36",
    colors: ["pink", "red", "magenta", "gray"],
    sizes: ["XS"],
    availability: ["Amsterdam"],
  },
  {
    id: 37,
    name: "Product #37",
    colors: ["green"],
    sizes: ["M"],
    availability: ["Paris"],
  },
  {
    id: 38,
    name: "Product #38",
    colors: ["white"],
    sizes: ["M"],
    availability: ["London", "Paris", "Budapest"],
  },
  {
    id: 39,
    name: "Product #39",
    colors: ["black", "magenta"],
    sizes: ["L"],
    availability: ["Amsterdam", "Copenhagen"],
  },
  {
    id: 40,
    name: "Product #40",
    colors: ["white", "gray"],
    sizes: ["XS", "XL"],
    availability: ["Prague"],
  },
  {
    id: 41,
    name: "Product #41",
    colors: ["black", "white", "pink", "gray"],
    sizes: ["XS", "M"],
    availability: ["Budapest"],
  },
  {
    id: 42,
    name: "Product #42",
    colors: ["blue", "white", "red"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 43,
    name: "Product #43",
    colors: ["blue", "magenta"],
    sizes: ["XXL"],
    availability: ["Budapest"],
  },
  {
    id: 44,
    name: "Product #44",
    colors: ["black", "yellow", "magenta"],
    sizes: ["M", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 45,
    name: "Product #45",
    colors: ["yellow", "gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 46,
    name: "Product #46",
    colors: ["blue"],
    sizes: ["XXS", "S"],
    availability: ["Amsterdam", "Prague", "Berlin"],
  },
  {
    id: 47,
    name: "Product #47",
    colors: ["blue", "white"],
    sizes: ["XXL"],
    availability: ["Paris", "Copenhagen", "Berlin"],
  },
  {
    id: 48,
    name: "Product #48",
    colors: ["red", "yellow", "magenta"],
    sizes: ["XS", "L"],
    availability: ["Budapest"],
  },
  {
    id: 49,
    name: "Product #49",
    colors: ["gray"],
    sizes: ["XXS", "M"],
    availability: ["Budapest"],
  },
  {
    id: 50,
    name: "Product #50",
    colors: ["red", "green", "gray"],
    sizes: ["S", "M", "XL", "XXL"],
    availability: ["Copenhagen"],
  },
  {
    id: 51,
    name: "Product #51",
    colors: ["red", "gray"],
    sizes: ["XXS"],
    availability: ["Budapest"],
  },
  {
    id: 52,
    name: "Product #52",
    colors: ["red", "yellow", "magenta"],
    sizes: ["M"],
    availability: ["Berlin"],
  },
  {
    id: 53,
    name: "Product #53",
    colors: ["gray"],
    sizes: ["XXS"],
    availability: ["Paris", "Copenhagen"],
  },
  {
    id: 54,
    name: "Product #54",
    colors: ["green"],
    sizes: ["M"],
    availability: ["Prague"],
  },
  {
    id: 55,
    name: "Product #55",
    colors: ["blue", "green"],
    sizes: ["XL", "XXL"],
    availability: ["London"],
  },
  {
    id: 56,
    name: "Product #56",
    colors: ["blue", "red", "yellow"],
    sizes: ["M"],
    availability: ["Copenhagen", "Prague", "Berlin"],
  },
  {
    id: 57,
    name: "Product #57",
    colors: ["white", "pink", "yellow", "magenta"],
    sizes: ["XXS", "XXL"],
    availability: ["London", "Paris", "Copenhagen"],
  },
  {
    id: 58,
    name: "Product #58",
    colors: ["pink"],
    sizes: ["XL"],
    availability: ["Amsterdam"],
  },
  {
    id: 59,
    name: "Product #59",
    colors: ["white"],
    sizes: ["S"],
    availability: ["Budapest"],
  },
  {
    id: 60,
    name: "Product #60",
    colors: ["blue", "white", "yellow"],
    sizes: ["XS"],
    availability: ["Budapest"],
  },
  {
    id: 61,
    name: "Product #61",
    colors: ["white", "red", "gray"],
    sizes: ["XXS"],
    availability: ["London"],
  },
  {
    id: 62,
    name: "Product #62",
    colors: ["yellow", "green"],
    sizes: ["XS"],
    availability: ["Copenhagen", "Budapest", "Prague"],
  },
  {
    id: 63,
    name: "Product #63",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Prague"],
  },
  {
    id: 64,
    name: "Product #64",
    colors: ["blue"],
    sizes: ["M", "XL"],
    availability: ["Amsterdam", "Paris", "Budapest"],
  },
  {
    id: 65,
    name: "Product #65",
    colors: ["blue", "gray"],
    sizes: ["XXS", "M", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 66,
    name: "Product #66",
    colors: ["red", "magenta", "green"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 67,
    name: "Product #67",
    colors: ["gray"],
    sizes: ["XL", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 68,
    name: "Product #68",
    colors: ["green"],
    sizes: ["S"],
    availability: ["Amsterdam", "Prague"],
  },
  {
    id: 69,
    name: "Product #69",
    colors: ["pink"],
    sizes: ["M"],
    availability: ["Paris"],
  },
  {
    id: 70,
    name: "Product #70",
    colors: ["blue", "green"],
    sizes: ["XS", "S", "M"],
    availability: ["Paris"],
  },
  {
    id: 71,
    name: "Product #71",
    colors: ["blue", "pink", "magenta"],
    sizes: ["L"],
    availability: ["Berlin"],
  },
  {
    id: 72,
    name: "Product #72",
    colors: ["black", "green"],
    sizes: ["M"],
    availability: ["Berlin"],
  },
  {
    id: 73,
    name: "Product #73",
    colors: ["black", "pink"],
    sizes: ["XS", "S", "XL", "XXL"],
    availability: ["Amsterdam"],
  },
  {
    id: 74,
    name: "Product #74",
    colors: ["white"],
    sizes: ["XS", "M"],
    availability: ["Copenhagen", "Prague", "Berlin"],
  },
  {
    id: 75,
    name: "Product #75",
    colors: ["gray"],
    sizes: ["L"],
    availability: ["Budapest"],
  },
  {
    id: 76,
    name: "Product #76",
    colors: ["blue"],
    sizes: ["S", "L"],
    availability: ["Copenhagen", "Budapest", "Prague"],
  },
  {
    id: 77,
    name: "Product #77",
    colors: ["white"],
    sizes: ["XS"],
    availability: ["London", "Amsterdam", "Prague", "Berlin"],
  },
  {
    id: 78,
    name: "Product #78",
    colors: ["magenta"],
    sizes: ["M"],
    availability: ["London", "Amsterdam", "Paris", "Prague"],
  },
  {
    id: 79,
    name: "Product #79",
    colors: ["white", "green"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 80,
    name: "Product #80",
    colors: ["gray"],
    sizes: ["XL"],
    availability: ["London", "Amsterdam", "Copenhagen", "Budapest", "Berlin"],
  },
  {
    id: 81,
    name: "Product #81",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Paris", "Berlin"],
  },
  {
    id: 82,
    name: "Product #82",
    colors: ["magenta", "green"],
    sizes: ["S", "L", "XL"],
    availability: ["London"],
  },
  {
    id: 83,
    name: "Product #83",
    colors: ["pink", "red", "green"],
    sizes: ["XXS", "XL"],
    availability: ["Copenhagen", "Berlin"],
  },
  {
    id: 84,
    name: "Product #84",
    colors: ["white", "magenta", "gray"],
    sizes: ["M"],
    availability: ["Paris"],
  },
  {
    id: 85,
    name: "Product #85",
    colors: ["blue", "gray"],
    sizes: ["S", "XL"],
    availability: ["London", "Paris", "Copenhagen", "Berlin"],
  },
  {
    id: 86,
    name: "Product #86",
    colors: ["black"],
    sizes: ["M", "L"],
    availability: ["Budapest"],
  },
  {
    id: 87,
    name: "Product #87",
    colors: ["blue", "red", "magenta", "gray"],
    sizes: ["XS", "S"],
    availability: ["London", "Amsterdam", "Copenhagen"],
  },
  {
    id: 88,
    name: "Product #88",
    colors: ["blue", "white", "gray"],
    sizes: ["XXS", "XXL"],
    availability: ["Berlin"],
  },
  {
    id: 89,
    name: "Product #89",
    colors: ["blue", "gray"],
    sizes: ["S", "XL"],
    availability: ["London", "Copenhagen"],
  },
  {
    id: 90,
    name: "Product #90",
    colors: ["black", "red", "green", "gray"],
    sizes: ["L", "XXL"],
    availability: ["Amsterdam", "Budapest"],
  },
  {
    id: 91,
    name: "Product #91",
    colors: ["gray"],
    sizes: ["XXS", "S", "L"],
    availability: ["Budapest"],
  },
  {
    id: 92,
    name: "Product #92",
    colors: ["white"],
    sizes: ["M", "XL"],
    availability: ["Berlin"],
  },
  {
    id: 93,
    name: "Product #93",
    colors: ["pink", "magenta"],
    sizes: ["L", "XL"],
    availability: ["Paris", "Berlin"],
  },
  {
    id: 94,
    name: "Product #94",
    colors: ["black"],
    sizes: ["L"],
    availability: ["Berlin"],
  },
  {
    id: 95,
    name: "Product #95",
    colors: ["black"],
    sizes: ["XXS", "L", "XL"],
    availability: ["Copenhagen"],
  },
  {
    id: 96,
    name: "Product #96",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Copenhagen", "Berlin"],
  },
  {
    id: 97,
    name: "Product #97",
    colors: ["blue", "gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 98,
    name: "Product #98",
    colors: ["red"],
    sizes: ["M"],
    availability: ["Berlin"],
  },
  {
    id: 99,
    name: "Product #99",
    colors: ["white", "red", "yellow", "gray"],
    sizes: ["XL"],
    availability: ["London", "Budapest", "Prague"],
  },
  {
    id: 100,
    name: "Product #100",
    colors: ["yellow"],
    sizes: ["M", "L", "XXL"],
    availability: ["Copenhagen"],
  },
  {
    id: 101,
    name: "Product #101",
    colors: ["pink"],
    sizes: ["XXS", "XS"],
    availability: ["Budapest"],
  },
  {
    id: 102,
    name: "Product #102",
    colors: ["blue", "white", "yellow", "magenta"],
    sizes: ["XS", "S"],
    availability: ["Budapest"],
  },
  {
    id: 103,
    name: "Product #103",
    colors: ["black", "magenta"],
    sizes: ["M"],
    availability: ["Paris"],
  },
  {
    id: 104,
    name: "Product #104",
    colors: ["white"],
    sizes: ["XXS", "S"],
    availability: ["Budapest"],
  },
  {
    id: 105,
    name: "Product #105",
    colors: ["blue", "magenta"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 106,
    name: "Product #106",
    colors: ["pink", "magenta"],
    sizes: ["XXS", "XS", "XXL"],
    availability: ["Amsterdam"],
  },
  {
    id: 107,
    name: "Product #107",
    colors: ["red", "magenta"],
    sizes: ["XS", "S"],
    availability: ["Budapest"],
  },
  {
    id: 108,
    name: "Product #108",
    colors: ["pink"],
    sizes: ["XS"],
    availability: ["London", "Prague"],
  },
  {
    id: 109,
    name: "Product #109",
    colors: ["gray"],
    sizes: ["XXS", "XS", "XXL"],
    availability: ["London", "Paris", "Prague"],
  },
  {
    id: 110,
    name: "Product #110",
    colors: ["yellow", "magenta"],
    sizes: ["S"],
    availability: ["London", "Copenhagen"],
  },
  {
    id: 111,
    name: "Product #111",
    colors: ["yellow", "gray"],
    sizes: ["S", "XL"],
    availability: ["Budapest"],
  },
  {
    id: 112,
    name: "Product #112",
    colors: ["red"],
    sizes: ["XXS", "XL"],
    availability: ["Budapest"],
  },
  {
    id: 113,
    name: "Product #113",
    colors: ["blue"],
    sizes: ["XXS", "S"],
    availability: ["Berlin"],
  },
  {
    id: 114,
    name: "Product #114",
    colors: ["magenta"],
    sizes: ["M", "XXL"],
    availability: ["London", "Paris", "Prague", "Berlin"],
  },
  {
    id: 115,
    name: "Product #115",
    colors: ["black", "white", "red"],
    sizes: ["M", "XL"],
    availability: ["Budapest"],
  },
  {
    id: 116,
    name: "Product #116",
    colors: ["gray"],
    sizes: ["XXS", "XS", "XL"],
    availability: ["London", "Budapest", "Berlin"],
  },
  {
    id: 117,
    name: "Product #117",
    colors: ["blue", "white", "magenta", "gray"],
    sizes: ["XL"],
    availability: ["Copenhagen"],
  },
  {
    id: 118,
    name: "Product #118",
    colors: ["black", "white", "green", "gray"],
    sizes: ["S"],
    availability: ["London"],
  },
  {
    id: 119,
    name: "Product #119",
    colors: ["black", "gray"],
    sizes: ["M"],
    availability: ["Amsterdam"],
  },
  {
    id: 120,
    name: "Product #120",
    colors: ["blue", "yellow", "green"],
    sizes: ["XXS", "M"],
    availability: ["Paris", "Prague", "Berlin"],
  },
  {
    id: 121,
    name: "Product #121",
    colors: ["black", "pink", "yellow"],
    sizes: ["XS", "M", "XXL"],
    availability: ["Copenhagen", "Prague"],
  },
  {
    id: 122,
    name: "Product #122",
    colors: ["blue", "yellow"],
    sizes: ["XXS"],
    availability: ["Paris", "Budapest"],
  },
  {
    id: 123,
    name: "Product #123",
    colors: ["green"],
    sizes: ["S", "XL", "XXL"],
    availability: ["Amsterdam"],
  },
  {
    id: 124,
    name: "Product #124",
    colors: ["gray"],
    sizes: ["XS"],
    availability: ["Copenhagen", "Prague"],
  },
  {
    id: 125,
    name: "Product #125",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 126,
    name: "Product #126",
    colors: ["blue", "red"],
    sizes: ["M"],
    availability: ["Amsterdam", "Copenhagen"],
  },
  {
    id: 127,
    name: "Product #127",
    colors: ["red", "yellow"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 128,
    name: "Product #128",
    colors: ["magenta", "green"],
    sizes: ["L", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 129,
    name: "Product #129",
    colors: ["black", "pink"],
    sizes: ["S"],
    availability: ["Paris", "Budapest"],
  },
  {
    id: 130,
    name: "Product #130",
    colors: ["green", "gray"],
    sizes: ["M"],
    availability: ["Amsterdam", "Paris", "Budapest", "Prague"],
  },
  {
    id: 131,
    name: "Product #131",
    colors: ["gray"],
    sizes: ["XXL"],
    availability: ["Paris", "Prague"],
  },
  {
    id: 132,
    name: "Product #132",
    colors: ["black", "white", "green"],
    sizes: ["S", "L"],
    availability: ["Berlin"],
  },
  {
    id: 133,
    name: "Product #133",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Prague"],
  },
  {
    id: 134,
    name: "Product #134",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["London", "Budapest"],
  },
  {
    id: 135,
    name: "Product #135",
    colors: ["black", "gray"],
    sizes: ["XXS", "XXL"],
    availability: ["Prague"],
  },
  {
    id: 136,
    name: "Product #136",
    colors: ["white", "gray"],
    sizes: ["XXS", "XL"],
    availability: ["Paris", "Prague"],
  },
  {
    id: 137,
    name: "Product #137",
    colors: ["red", "yellow", "green"],
    sizes: ["XS", "M", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 138,
    name: "Product #138",
    colors: ["white", "pink"],
    sizes: ["L"],
    availability: ["Berlin"],
  },
  {
    id: 139,
    name: "Product #139",
    colors: ["green", "gray"],
    sizes: ["XS", "XL", "XXL"],
    availability: ["Paris", "Budapest", "Berlin"],
  },
  {
    id: 140,
    name: "Product #140",
    colors: ["yellow"],
    sizes: ["M"],
    availability: ["Amsterdam"],
  },
  {
    id: 141,
    name: "Product #141",
    colors: ["red"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 142,
    name: "Product #142",
    colors: ["black", "yellow"],
    sizes: ["XL"],
    availability: ["Amsterdam", "Prague"],
  },
  {
    id: 143,
    name: "Product #143",
    colors: ["black", "white", "magenta"],
    sizes: ["XS"],
    availability: ["London", "Copenhagen", "Budapest"],
  },
  {
    id: 144,
    name: "Product #144",
    colors: ["black", "green", "gray"],
    sizes: ["XL"],
    availability: ["Copenhagen"],
  },
  {
    id: 145,
    name: "Product #145",
    colors: ["blue", "yellow"],
    sizes: ["XXL"],
    availability: ["Budapest"],
  },
  {
    id: 146,
    name: "Product #146",
    colors: ["red", "magenta"],
    sizes: ["XXS", "S"],
    availability: ["Budapest"],
  },
  {
    id: 147,
    name: "Product #147",
    colors: ["black"],
    sizes: ["XXS", "XS"],
    availability: ["London"],
  },
  {
    id: 148,
    name: "Product #148",
    colors: ["white"],
    sizes: ["XL"],
    availability: ["Berlin"],
  },
  {
    id: 149,
    name: "Product #149",
    colors: ["blue", "red", "yellow"],
    sizes: ["XXS", "M"],
    availability: ["Budapest"],
  },
  {
    id: 150,
    name: "Product #150",
    colors: ["blue", "white"],
    sizes: ["XXS", "S"],
    availability: ["Amsterdam", "Berlin"],
  },
  {
    id: 151,
    name: "Product #151",
    colors: ["magenta"],
    sizes: ["XS", "S"],
    availability: ["London", "Copenhagen"],
  },
  {
    id: 152,
    name: "Product #152",
    colors: ["gray"],
    sizes: ["S", "L", "XXL"],
    availability: ["Copenhagen"],
  },
  {
    id: 153,
    name: "Product #153",
    colors: ["green"],
    sizes: ["L", "XXL"],
    availability: ["Amsterdam"],
  },
  {
    id: 154,
    name: "Product #154",
    colors: ["gray"],
    sizes: ["L"],
    availability: ["Amsterdam", "Paris", "Berlin"],
  },
  {
    id: 155,
    name: "Product #155",
    colors: ["blue"],
    sizes: ["XXS", "XL"],
    availability: ["Copenhagen", "Budapest"],
  },
  {
    id: 156,
    name: "Product #156",
    colors: ["white", "gray"],
    sizes: ["XXS"],
    availability: ["Budapest"],
  },
  {
    id: 157,
    name: "Product #157",
    colors: ["red"],
    sizes: ["XS", "S"],
    availability: ["Budapest", "Prague"],
  },
  {
    id: 158,
    name: "Product #158",
    colors: ["blue", "red", "magenta"],
    sizes: ["M"],
    availability: ["Copenhagen", "Berlin"],
  },
  {
    id: 159,
    name: "Product #159",
    colors: ["gray"],
    sizes: ["M", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 160,
    name: "Product #160",
    colors: ["white"],
    sizes: ["XXS", "XS"],
    availability: ["Prague"],
  },
  {
    id: 161,
    name: "Product #161",
    colors: ["white", "yellow", "magenta", "gray"],
    sizes: ["XXS", "S"],
    availability: ["London", "Budapest", "Berlin"],
  },
  {
    id: 162,
    name: "Product #162",
    colors: ["blue", "magenta", "gray"],
    sizes: ["L", "XXL"],
    availability: ["Budapest", "Berlin"],
  },
  {
    id: 163,
    name: "Product #163",
    colors: ["magenta"],
    sizes: ["XXS", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 164,
    name: "Product #164",
    colors: ["red", "yellow", "gray"],
    sizes: ["S"],
    availability: ["Budapest"],
  },
  {
    id: 165,
    name: "Product #165",
    colors: ["blue", "gray"],
    sizes: ["L", "XXL"],
    availability: ["Amsterdam", "Copenhagen", "Berlin"],
  },
  {
    id: 166,
    name: "Product #166",
    colors: ["white", "pink", "gray"],
    sizes: ["XL"],
    availability: ["Amsterdam", "Prague", "Berlin"],
  },
  {
    id: 167,
    name: "Product #167",
    colors: ["black", "red", "green"],
    sizes: ["S"],
    availability: ["Amsterdam", "Prague"],
  },
  {
    id: 168,
    name: "Product #168",
    colors: ["blue", "red"],
    sizes: ["M"],
    availability: ["Amsterdam"],
  },
  {
    id: 169,
    name: "Product #169",
    colors: ["white", "yellow", "gray"],
    sizes: ["M"],
    availability: ["Paris", "Copenhagen", "Berlin"],
  },
  {
    id: 170,
    name: "Product #170",
    colors: ["black", "gray"],
    sizes: ["M"],
    availability: ["Berlin"],
  },
  {
    id: 171,
    name: "Product #171",
    colors: ["black", "red", "green"],
    sizes: ["M"],
    availability: ["London", "Prague"],
  },
  {
    id: 172,
    name: "Product #172",
    colors: ["green", "gray"],
    sizes: ["XXS"],
    availability: ["Prague"],
  },
  {
    id: 173,
    name: "Product #173",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 174,
    name: "Product #174",
    colors: ["white", "pink", "red", "green"],
    sizes: ["M"],
    availability: ["Amsterdam"],
  },
  {
    id: 175,
    name: "Product #175",
    colors: ["black", "red", "green", "gray"],
    sizes: ["XS"],
    availability: ["Prague", "Berlin"],
  },
  {
    id: 176,
    name: "Product #176",
    colors: ["white"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 177,
    name: "Product #177",
    colors: ["pink", "red", "magenta"],
    sizes: ["M"],
    availability: ["Prague"],
  },
  {
    id: 178,
    name: "Product #178",
    colors: ["blue", "green"],
    sizes: ["L", "XXL"],
    availability: ["Amsterdam"],
  },
  {
    id: 179,
    name: "Product #179",
    colors: ["gray"],
    sizes: ["XS", "XL"],
    availability: ["Copenhagen", "Budapest", "Prague"],
  },
  {
    id: 180,
    name: "Product #180",
    colors: ["blue", "white", "pink", "magenta"],
    sizes: ["M"],
    availability: ["Budapest", "Prague"],
  },
  {
    id: 181,
    name: "Product #181",
    colors: ["red"],
    sizes: ["XS", "L", "XXL"],
    availability: ["Amsterdam", "Paris"],
  },
  {
    id: 182,
    name: "Product #182",
    colors: ["white", "red", "magenta"],
    sizes: ["XS"],
    availability: ["London"],
  },
  {
    id: 183,
    name: "Product #183",
    colors: ["green"],
    sizes: ["XL"],
    availability: ["Budapest"],
  },
  {
    id: 184,
    name: "Product #184",
    colors: ["white", "pink", "green"],
    sizes: ["XS"],
    availability: ["Amsterdam", "Budapest"],
  },
  {
    id: 185,
    name: "Product #185",
    colors: ["yellow", "magenta", "gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 186,
    name: "Product #186",
    colors: ["red"],
    sizes: ["XXS"],
    availability: ["Budapest"],
  },
  {
    id: 187,
    name: "Product #187",
    colors: ["gray"],
    sizes: ["XXS", "XL"],
    availability: ["Amsterdam", "Copenhagen", "Prague"],
  },
  {
    id: 188,
    name: "Product #188",
    colors: ["blue", "white"],
    sizes: ["S", "L"],
    availability: ["London", "Berlin"],
  },
  {
    id: 189,
    name: "Product #189",
    colors: ["gray"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 190,
    name: "Product #190",
    colors: ["black", "white", "pink", "red"],
    sizes: ["XXS"],
    availability: ["Prague"],
  },
  {
    id: 191,
    name: "Product #191",
    colors: ["pink"],
    sizes: ["S", "XXL"],
    availability: ["Budapest"],
  },
  {
    id: 192,
    name: "Product #192",
    colors: ["black", "pink", "yellow"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 193,
    name: "Product #193",
    colors: ["pink", "red"],
    sizes: ["XXS", "XXL"],
    availability: ["Amsterdam", "Paris"],
  },
  {
    id: 194,
    name: "Product #194",
    colors: ["black", "pink", "red", "green"],
    sizes: ["XXS"],
    availability: ["Amsterdam", "Copenhagen", "Prague"],
  },
  {
    id: 195,
    name: "Product #195",
    colors: ["blue", "yellow"],
    sizes: ["XS", "M"],
    availability: ["Budapest"],
  },
  {
    id: 196,
    name: "Product #196",
    colors: ["gray"],
    sizes: ["M", "XL"],
    availability: ["Paris", "Prague"],
  },
  {
    id: 197,
    name: "Product #197",
    colors: ["pink", "green"],
    sizes: ["M"],
    availability: ["Budapest"],
  },
  {
    id: 198,
    name: "Product #198",
    colors: ["red", "green", "gray"],
    sizes: ["XXS"],
    availability: ["Amsterdam"],
  },
  {
    id: 199,
    name: "Product #199",
    colors: ["blue", "pink", "red"],
    sizes: ["M"],
    availability: ["Prague"],
  },
];

const uniques = (array) =>
  array.filter((item, index) => array.indexOf(item) === index);

const allColors = uniques(
  products.map((product) => product.colors).flat()
).sort();

const allSizes = uniques(
  products.map((product) => product.sizes).flat()
).sort();

const allAvailabilities = uniques(
  products.map((product) => product.availability).flat()
).sort();

export default products;

export { allColors, allSizes, allAvailabilities };
